package com.hadis.widget;

import java.util.Random;

public class HadisData {

    private static final Random random = new Random();

    // {text, source, category}
    // FR=Fethur-Rabbani, YG=Yakaran Gonuller, KK=Kulli Kaideler
    private static final String[][] ENTRIES = {

        // ========== FETHUR-RABBANI (40) ==========
        {"Kader basa geldigi zaman gonderene kafa tutmak, inanci oldurur; Tevhid nurunu sondurur; tevekkul ve ihlasi yok eder. Akilli olan odur ki basa gelen isle mucadele etmez, kaderin hukmu onunde boyun eger. Kader sana ne getirirse onu kabul et. Onu gonderenin hikmetine inan. Dunya nimetlerini gonlune sokma; eline al, yeter. Kalbe giren dunya, onu karanliga goturur. Elde kalan dunya ise isine yarar.", "Fethur-Rabbani, 1. Sohbet", "FR"},
        {"Geliniz, varligimizi bir yana atarak Ona kosalim. Bu yolda biraz da perisanlik cekelim. Halk bizi rezil gorsun, ne cikar! Biraz zahmet ceksen, Ona vardiktan sonra hepsi gecip gider. Icimize ve disimiza sultan kesilen nefsimizi Hak yoluna cevirelim. Nefsin sultanligi ancak Hak yoluna girilince sona erer. Bu yolda yuruyen, evvela yorulur, sonra dinlenir. Evvela aglar, sonra guler. Evvela darlik gorur, sonra genislik bulur.", "Fethur-Rabbani, 1. Sohbet", "FR"},
        {"Yalniz kaldigin zaman seni kotu isten koruyacak duyguya muhtacsin. Ayak kaymasini onleyecek tedbirin olmali. Hakkin her an seni kontrol ettigini icinden sezmelisin. Bu dusunceler varligini sarmali. Benligini bu ogutlerle donattiktan sonra nefisle cenge cikmak kabil olur. Nefis, seni karanliklara goturur; ama sen isik ol, karanliga galip gel. Gunduzun karanliga galip gelmesi gibi, imanin da nefse galip gelmesi gerekir.", "Fethur-Rabbani, 1. Sohbet", "FR"},
        {"Ey evlad! Dunyalik toplarken dikkatli ol. Gece odun toplayan gibi olma. Elini attigin zaman neyi alacagini onceden kestirmelisin. Gece odun toplayan eline gireni bilmez. Seni de ona benzetiyorum. Ayik ol, sonra felaketin azim olur. Dunya geceleri karanlik olur. Kendine isik bul. O isik, iman ve takva isigidir. Onsuz ne toplarsan topla, eline gecen zehir olur. Goz acik olmadan toplanan dunya mali, sahibini yer bitirir.", "Fethur-Rabbani, 4. Sohbet", "FR"},
        {"Hakla cekisme. Malin azaldi diye Onu itham etme. Sucu evvela kendinde ara. Allaha emir mi vereceksin? Her is senin keyfine gore olsun istiyorsun. En buyuk hukum senin mi olmali yoksa Onun mu? Sen mi fazla biliyorsun yoksa O mu? Senin merhametin Ondan cok mu? Hakkin her verdigi yerindedir. Bazen vermemesi de vermesidir. Bazen darligi da genisligidir. Ama bunu anlayacak goz lazim, his lazim, kalp lazim.", "Fethur-Rabbani, 4. Sohbet", "FR"},
        {"Dunyada Onunla sohbet istiyorsan sessiz ol. Sakin ve sessiz ol. Allahin sevgili kullari edeplidir. Onun gozunde en buyuk edep gereklerini yerine getirirler. Attiklari her adim, acik izne baglidir. Kalplerini hos etmeyecek hicbir ise yakin durmazlar. Onlar Hakkin huzurunda bir mumya gibi dururlar. Kipirti olmaz, gurultu olmaz. Sadece kalpleri cosar, gozyaslari akar, iclerinden firtinalar kopar; ama disarisi sakindir.", "Fethur-Rabbani, 4. Sohbet", "FR"},
        {"Ey hasta! Hastaliginin gecmesini mutlak olarak isteme. Afiyetin her zaman yararli olacagini sana kim dedi? Simdi hastasin imanin var; saglam olunca bu imani kaybetmeyecegini kim temin eder? Dunyaliga dalar, Allahi, Peygamberi unutursun. Akilli ol, her olur olmaz seyin pesine kosma. Hastalik bazen kalp icin sifadir. Beden acisi cekerken ruh sifa bulur. Gozyas dokerken kalp temizlenir. Dert cekerken manevi makamlar acilir.", "Fethur-Rabbani, 3. Sohbet", "FR"},
        {"Sen Hakki aradigini soyluyorsun; halbuki halki ariyorsun. Ben Mekkeye gidiyorum deyip Horasan yolunu tutana benziyorsun. Horasana yakin oldukca Mekkeden uzak kalirsin. Ic alemin temiz oldugunu soyluyorsun; fakat onlardan hem korkuyor hem de bir seyler bekliyorsun. Hem Hakki istiyorum diyorsun hem de halktan bir sey umuyorsun. Bu ikisi bir arada olmaz. Bir kalbe iki sevgi sigmaz. Ya Hak ya halk. Sec birini.", "Fethur-Rabbani, 10. Sohbet", "FR"},
        {"Ey Allahin kullari, nefsinizi Ona teslim ediniz. Soyliyiniz: Nefis, mal, cennet senin olsun. Bize Zatini ver. Baskasini istemiyoruz. Bize ev verirsin, icinde Sen olmayinca neyleriz? Yola ciktigimizda yol arkadasimiz Sen olmadiktan sonra yolculugu ne yapariz? Her nimeti Sen verirsin; ama nimet degil, nimeti vereni isteriz. Her guzellik Senden gelir; ama guzellik degil, guzelligi yaratani dileriz.", "Fethur-Rabbani, 12. Sohbet", "FR"},
        {"Sizde nifak cogaldi, ihlas azaldi. Sozler cok fakat onlara uygun is yok. Isi olmayan soz hicbir seye yaramaz. Sahibine felaket getirir. Onune is gelmeyen soz kapisiz eve benzer, merdivensiz binadir. Icinden iyilik gecmeyen hazineye benzer. Amelsiz soz kuru davadan ibarettir. Sozu cok, isi az olana yaziklar olsun. Sozun degeri amelle olculur. Ameli olmayan sozun agirlik degil hafiflik getirdigini bilin.", "Fethur-Rabbani, 20. Sohbet", "FR"},
        {"Irfan sahiplerine uyunuz. Onlarla arkadas olunuz. Onlarin hali baskadir, sizinkine benzemez. Bilirler, is tutarlar. Halka dilencilik icin degil nasihat icin kosarlar. Kalbinizi Hakka cevirmekten baska gayeleri yoktur. Kalp yuzlerini Hakka cevirmislerdir. Onlar sizin gordugunuzu gormez, sizin duydugunuzu duymaz. Onlarin gozleri baska gorur, kulaklari baska duyar. Zira kalp gozleri acilmistir.", "Fethur-Rabbani, 22. Sohbet", "FR"},
        {"Musibetleri sakli tutmak, Ars hazinelerinden birine sahip olmak kadar buyuktur. Derdini Hakka soyleyecegine halka anlatiyor, onlardan medet umuyorsun. Halbuki senin derdine deva verecek olan yalniz Haktir. Sabret, gizle ve Rabbine sigin. Derdini Hakka acmak ibadettir; halka acmak ise zillete dusturur. Sikayetini Ona yap, insanlara degil. Zira insanlar sana merhem suremez; ama Allah bir anda sifasini verir.", "Fethur-Rabbani, 26. Sohbet", "FR"},
        {"Bir kul dustugu darlik halinde sabir yolunu tutarsa, karanlik yollara cira ile girerse, darligi genislige cevrilir. Hata karanligini ibadet lambasi aydinlatir. Rahmet nazari o kula gelir. Nasibi ummadigi yollardan verilir. Yusuf Peygamber sabirla o buyuk devlete kavustu. Zindandan saraya cikti. Karanliktan aydinliga erisiti. Sabirda buyuk sirlar gizlidir. Sabredene verilen mukafatin hududu yoktur.", "Fethur-Rabbani, 35. Sohbet", "FR"},
        {"Nefsini cihad potasinda erit. Nefisle olan cihad, dis alemdekinden daha zordur. Nefis butun arzularindan kesilir. Sonra tek yol acilir. O da Allahin emri yolu. Nefis, en buyuk dusmandir. Onu yenmek butun zaferlerin ustundedir. Her gun nefsinle savas. Ona istedigini verme. Istediginin aksini yap. Acikinca bekle, doydugunda dur. Nefis zayifladikca kalp kuvvetlenir. Kalp kuvvetlendikce Hak nuru parlar.", "Fethur-Rabbani, 42. Sohbet", "FR"},
        {"Mecnun gibi olmalisin. O, kalbinde sevgi yer ettigi zaman halk arasindan cikti. Yalniz olmayi istedi. Halkin ne ovmesini dinledi ne de kotulemesine kulak asti. Sordular: Sen kimsin? Soyledi: Leyla. Neredensin? Leyla. Nereye? Leyla. Baskalarini gozu gormuyordu. Asik olan her seyi masukundan gorur. Her yerde onu bulur. Her seste onun sesini duyar. Gercek asik, masukunu her zerrede arar ve bulur.", "Fethur-Rabbani, 41. Sohbet", "FR"},
        {"Calis, islerde sen olmayasin; yapan ve eden O ola. Halin yikayici onundeki oluye benzesin. Cumle tedbiri birak. Onun onunde iman ayaginla dur, nefsini gorme. Irade et ki iradesiz olasin. Iste ki isteksiz olasin. Varligindan soyun ki gercek varliga eresin. Kendini birak ki Hak seni tutsun. Kendi gucune guvenme ki Onun gucu seni kusatsin. Fani ol ki baki olasin.", "Fethur-Rabbani, 47. Sohbet", "FR"},
        {"Marifet sahibinin zahirde yaptigi isler, ic alemindeki islere nisbetle bir zerre sayilir. Duygulari sakindir ama kalbi daima hareket eder. Bas gozu uyur, kalp gozu uyumaz. Uyur ama kalbi isleri gorur, Hakki anar. Elinde tesbih oldugu halde uyur, uyandigi zaman onu yine cevrilirken gorurmus. Bu hal, kalbin uyanikliginin isaretidir. Beden yorulur uyur, ama kalp Rabbini anmaktan bir an bile geri durmaz.", "Fethur-Rabbani, 68. Sohbet", "FR"},
        {"Bir kimse ki Allah icin tevazu eder, Allah onu yukseltir. Kibir yolunu tutan dusurulur. Azla yetinene cok gelir. Zillet halini sabirla karsilayana izzet gelir. Bulundugun hale razi ol, islerin aniden degisir. Verilmiyor diye bagirirsan, verilince utanirsin. Tevazu, yuksekligin merdivenidir. Kibir ise alcakligin baslagidir. Sakin kibir kapsindan girme; zira o kapidan girenin sonu her zaman husrandir.", "Fethur-Rabbani, 59. Sohbet", "FR"},
        {"Ey evlad! Allahin hilmine guvenme. Onun tutusu sedittir. Bir tutarsa yikilirsin. Su cahil bilginler seni aldatmasin. Onlarin cumle bilgileri aleyhlerine cikar. Allahin hukumlerini bilirler; o varlik sahibinin zatindan tamamen gafil gezerler. Ilim baska, irfan baska. Ilim kitaptan ogrenir, irfan kalpten duyar. Ilim akli doldurur, irfan kalbi doldurur. Ilim tartistirir, irfan sustirur. Irfan sahibi az konusur cok dinler.", "Fethur-Rabbani, 9. Sohbet", "FR"},
        {"Dunyalik elde olur, cepte olur. Iyi ve yararli binalar yapmak icin caiz. Ama onlari kalbe sokmak olmaz. Dunyaligin kalp kapisinda beklemesi olur ama iceri girmesi asla. Dunyaliktan gecici seyleri kalbin kosesine yerlestirirsen sende de hayir kalmaz. Kalp bir hukumdardir; tahtina neyi oturttursan o hukmeder. Dunyayi oturtursan dunya hukumdar olur. Hakki oturtursan Hak hukumdar olur. Sec bakalim kimi oturtuyorsun.", "Fethur-Rabbani, 53. Sohbet", "FR"},
        {"Iman ki yakin derecesine cikar, yakin ki marifet halini alir, marifet ki ilim olur: Iste o zaman Haktan guzellikler gelir ve sen diledigini yapar olursun. Zengin kisilerden mal alir fakirlere dagitirsin. Kalp ve sir elinle riziklar tasimaya baslarsin. Bu hal kolay ele gecmez. Uzun bir yolculuk ister. Sabir ister, gayret ister, gozyasi ister. Her mertebe bir oncekinin ustune bina edilir. Acele etme, yol uzundur ama sonunda muradina erersin.", "Fethur-Rabbani, 68. Sohbet", "FR"},
        {"Yalanci olma. Sana iki kalp verilmedi. Sinen bir kalp tasir. O bir seyle dolunca ikincisi sigmaz. Allah soyle buyurur: Allah bir kisinin sine bosluguna iki kalp yerlestirmedi. Bir kalp ki hem Hakki hem de halki sever, o sihhat bulamaz. Kalp tektir, sevgi tektir, yol tektir. Iki yolda birden yurunemez. Kalp ya Hakka bakar ya halka. Ortasi yoktur. Bu secimi yapamayan, yolda kalir, menzile varamaz.", "Fethur-Rabbani, 61. Sohbet", "FR"},
        {"Veli kullarin kimi dunyada kimi ahirette Hakka kavusur. Kalp ve sir alemi ile dunyada Hakka vasil olan azdir. Kavusan rahat ve huzura erer. Ama onceleri aglamakla sizlamakla gecer. Allah yolcularinin darligi gecmez. Ta Hak Tealaya kavusuncaya kadar. Bu yolda gozyasi azik, sabir binek, ihlas yol arkadasidir. Bu ucunu yanina alandan yolda kalamaz. Gozyassiz sabir kurudur, sabirsiz gozyasi zaaftir. Ucunu bir tut.", "Fethur-Rabbani, 28. Sohbet", "FR"},
        {"Ibadet bir sanattir; onu yapanlar Allahin sevgili kullaridir. Varligini Hak varligina katanlar ve Ondan baska seyi gormeyenler. Farzet halkin teveccuhu sana geldi; olum aninda neye yarar? Olum aninda aranizda ucurumlar olur. Seni kurtaramazlar. O an yalniz Rabbin var. O an ne malin ise yarar ne mulkun. O an sadece amelin konusur. O an sadece imanin isik verir. O an icin simdi hazirlan, sonra gec olur.", "Fethur-Rabbani, 11. Sohbet", "FR"},
        {"Ey cemaat! Yakinda oluler olacaksiniz. Size aglayacaklar. Onlar aglamaya baslamadan siz gozyaslarinizi akitiniz. Sizin bir yigin hatalariniz var. O hatalarin sonu nereye kadar uzar bilinmez. Kalpleriniz dunya sevgisi ile hasta. Dunya hirsi gonlunuzu sarmis. Dunyadan kalbinizi beri alin ve temizleyin. Dunyayi birakin Hakka yonelin. Dinin selameti sermayedir. Iyi isler de onun karidir.", "Fethur-Rabbani, 18. Sohbet", "FR"},
        {"Iman sahibi odur ki bela geldigi zaman sabreder. Allah yararsiz hicbir bela indirmez. Her bela bir iyiligin oncusudur. Bu iyilik ya dunya icin veya ahiret icin olur. Imanli kimse belaya sabirla karsi koyar. Allah gonderdigi icin razi olur. Rabbini itham etmez. Nicin geldi diye cikismaz. Mumin, inandigi ile ugrasir. Bu ugrasma imanliga belayi hatirlatmaz. Bela muminin mihenk tasidir; altin atese girmeden saf olmaz.", "Fethur-Rabbani, 7. Sohbet", "FR"},
        {"Buyuklerden birine ilmi nasil tahsil ettigini sordular. Cevap verdi: Kuslarin erken kalkismasi, devenin tahammulu, domuzun hirsi, kopegin yaltaklanmasi uzerimde derin tesirler yapti. Onlari gordum, bir hayvan olduklari halde yaptiklari ise baktim. Ben de insanim, onlarin hareketinden ibret aldim. Kus gibi erken kalktim. Ilmin butun agirligini cektim. Ilme karsi bir ihtiras duydum. Ilim sahiplerinin yaninda sabretim.", "Fethur-Rabbani, 24. Sohbet", "FR"},
        {"Ey evlad! Aklini basina al. Aceleci olma. Acele ile eline fazla bir sey girmez. Ivedi hareketle sabahi getirmen kolay olmaz. Sabahi beklerken acele etme. Baska seyle ugras. Ibadet et. O kendiliginlen gelir. Gunduzleri kendine mesgale bul; aksam kendiliginlen gelir. Izan sahibi ol. Kullarla iyi gecin. Kullara zulmetme. Hakkin olmayan seyi ellerinden almaya kalkisma. Onlar birer vekildir. Sabir ile bekle.", "Fethur-Rabbani, 23. Sohbet", "FR"},
        {"Hakkin kudretini gormedikce halkin verdiklerini kabul etme. Onlarin vermesini Hakkin kudreti ile gor; sonra al. Hak yakinligi dehset verir. Sayet bir dehset duymuyorsan, sakin Onun yakinligindan dem vurma, sonra yalanci oldugun yuzune vururlar. Insan iyi tevbe ederse imani sihhat bulur ve artar. Hakka itaatle iman artar, isyanla eksilir. Bu artis ve eksilis daima devam eder. Iman canli bir seydir, beslenmezse zayiflar.", "Fethur-Rabbani, 21. Sohbet", "FR"},
        {"Tasavvuf ehli cimri olmaz. Cunku cimrilik yapmasi icin elinde bir seyi yoktur. O her seyi biraktigi iddiasindadir. Birine bir sey verse Hakkin rizasi icin verir, kendisi icin degil. Onun kalbi varliklardan ve suretlerden temizlenmistir. Onun dostu da dusmani da olmaz; bu yuzden ne ovenin sozune sevinir ne kotuleyenin sozune uzulur. O herkese ayni gozle bakar. Cunku gozunde Haktan gayri kimse yoktur.", "Fethur-Rabbani, 58. Sohbet", "FR"},
        {"Halkla olduktan sonra Hakki gormen mumkun olmaz. Dunyayi gordukten sonra ahireti bilmen nasip olmaz. Bir yaninda dunya bagi obur yaninda ahiret sevgisi olursa onlari Yaratani bulmak nice umilir? Her fani varliktan tamamen siyrilirsan sir alemin Rabbinle karsilasir. Bu distan anlasilmaz, ic alemin halleridir. Iyi isler kalbe yarar, mana alemini bulmak sirra hastir. Allah yolculari kendi yaptiklari iyi isi gormezler.", "Fethur-Rabbani, 63. Sohbet", "FR"},
        {"Kotuluge karsi kendinizi daimi oruca alistiriniz. Oz varliginizi daimi namaza, eksiksiz ve kesintisiz huzura alistiriniz. Sabri hicbir zaman elden birakmayiniz. Nefsinizi boylece eziniz. Bir kula nefsi bos arzudan almak nasip olunca Mevlasini o dem bulur. Nefis terbiye edilmedikce kalp aydinlanmaz. Kalp aydinlanmadikca sir acilmaz. Sir acilmadikca Hak yaklinligi nasip olmaz.", "Fethur-Rabbani, 49. Sohbet", "FR"},
        {"Ey ahiret yoluna koyulan, o yola daha once girenleri delil tut. Onder zatin cocugu ol, ona uy. Butun yukunu onun onune dok. Onunla yola koyul. Bazen saginda bazen solunda bazen gerisinde yola devam et. Sakin onun gorusu disina cikma. Boyle yaparsan maksuduna kavusursun. Bu yolda rehbersiz yurumek corak bir colde pusulasiz yol almaya benzer. Yolun yildizlari buyuklerdir; onlara bakarak yuruyeni Hak muradina erdirir.", "Fethur-Rabbani, 70. Sohbet", "FR"},
        {"Dogru insanlar gecenin ve gunduzun cogunu ibadetle gecirirler. Adetler onlara uzak olur. Gunluk gecimlerini kolay kazanirlar. Az calisir, dogru olur. Dogruluk onlari zengin eder. Kazandiklarini yemekle emrolunduklari icin huzurla yerler. Her sey onlara ozunu gosterir. Her varlik parlaklik kazanir. Cok kere onlarin dertleri gonullerinde kalir. Istekleri verilmeyince sabra devam ederler. Boyleliklerin sonu her zaman hayirdir.", "Fethur-Rabbani, 11. Sohbet", "FR"},
        {"Hak Teala peygamberlerin, sevdigi velilerin ve salih kullarin kalbine sahiptir. Oraya baska sevginin girmesini istemez. Calib, calismak butun nebilerin yaptigi seydir. Sanati olmayan hicbir nebi bulunmaz. Halktan bir sey alan varsa o da fakirlere vermek icindir. Ey dunya sarabini icerek sehvet batagina girenler, sarhos olarak kotu heveslere kapilip kalmanin felaketini mezar cukurunda anlarsiniz.", "Fethur-Rabbani, 47. Sohbet", "FR"},
        {"Kalbinin telefonu ile daima Hakki ara. Ona baglan. Ondan iste. O verir hem cok verir hem guzel verir. Sen yalniz Ona abd ol, yalniz Ondan iste. Basini Onun kapisindan kaldirma. Kapinin onunde sabir ile bekle. Kapilir, zamaninda acilir. Vaktinden once kapiya vurmak edepsizliktir. Ama kapida beklemek edeptir. Bekle, bekleten de sabredeni de sever.", "Fethur-Rabbani, 5. Sohbet", "FR"},
        {"Sizin cogunuz dunyayi diler, pek azi da ahireti. Dunya ve ahiretin Rabbini isteyen ise nadir sayilir. Iste sana bu zumreyi bulmak duser. Onlari bul ve edepli ol. Onlarla cekisme ve niza cikarma. Onlarin halini eksik bilme, sonra manevi halinde noksanlik ortaya cikar. Akilli olunuz; siz yaptiginiz islerde Hakka dusmanlik tasliyorsunuz. Halbuki Onun yaninda degeriniz bir sinek kanadi kadar kiymete bile degmez. Ihlasli olun.", "Fethur-Rabbani, 55. Sohbet", "FR"},
        {"Nefsin yuzune gulme. Sana bin kelime soz etse ancak birine cevap ver. Nefis maddi arzulara dair bir sey dilerse iptal et. Istegini tehir eyle. Nefse arzusunun yerine gelmemesi aci gelir. Bu aciya dayanirsa iyilik bulur. Sabirla nefsi sabra yoneltmeye cabalarsan Ilahi tecellilere mazhar olursun. Nefis bir cocuk gibidir; ona terbiye lazim. Serbest biraksan yikip deviren sirarak bir vahsi olur.", "Fethur-Rabbani, 42. Sohbet", "FR"},
        {"Sizin cogunuz Hakkin nurundan, Islamin ruhundan mahrum ve onlara karsi perdelenmis. Islam iddiasini yapar ama onun hakikatinden haberi yoktur. Islamin yalniz ismi size ne fayda saglar ki onun adi ile yetinirsiniz. Disaridan sartlarini yerine getirirsiniz ama hakikatini asla bilmezsiniz. Islam bir kabugun icindeki ozdur. Siz kabukla yetiniyorsunuz. Oze inmeden Islam yasanmis olmaz. Kabugu kir, oze ulas.", "Fethur-Rabbani, 72. Sohbet", "FR"},
        {"Allah dilerse guclugu olmayan rahatlik verir. Gariplik bilmeyen unsiyet verir. Yalnizlik hissetmeyen arkadas verir. Fakirlik endisesi tasimayen zenginlik verir. Her sey Onun elindedir. Isterse bir anda halini degistirir. Gece gunduz olur, kis bahar olur, dert derman olur, gozyasi tebessume donusur. Sen sadece Ona guven ve bekle. O en guzel zamanda en guzel sekilde verir.", "Fethur-Rabbani, 10. Sohbet", "FR"},

        // ========== YAKARAN GONULLER (40) ==========
        {"Allahim! Senden hidayet, takva, iffet ve gonul zenginligi isterim. Kalbimi nurlandir. Gozumu nurlandir. Kulagimi nurlandir. Sagimi nurlandir. Solumu nurlandir. Ustumu nurlandir. Altimi nurlandir. Onumu nurlandir. Arkemi nurlandir. Bana buyuk bir nur ver. Her tarafimi nurla donat. Gozumun gordugunu nurla aydinlat. Kulagimin duydugunu nurla sule. Butun varligimi nurla sarip sarmala.", "Yakaran Gonuller, Nur Duasi", "YG"},
        {"Ey Rahmetinle kalbimi hidayet buyurman diledigim Allahim! Hatalarimi duzelt, bana dogruyu goster, sevdigim ve istedigim seylerin hayirlisi ne ise onu ver. Beni her turlu kotuluk, fitne ve zarardan koru. Her hukumde bu kuluna muvaffakiyet ihsan et. Sehitlerin makamindan, said ve bahtiyar kullarinin guzel hayatindan ve dusmanlara karsi zafer kazanmaktan beni mahrum etme.", "Yakaran Gonuller, Genel Dua", "YG"},
        {"Yuce Allahim! Enisim Sen ol ve beni yalnizlik hissi de dahil her turlu korkudan emin kil. Belalardan afetlerden helake goturebilecek yollardan dunyada ve ukbada gam kederden muhafaza buyur! Rabbim! Sen asla sozunden donmez, vaad ettiklerine muhalif bir is islemezsin; ne olur bize olan vaadlerini de lutfet! Rahmeti merhameti refeti ve sefkati sonuz olan Rabbim, bu aci kulunu sana sigindiriyor.", "Yakaran Gonuller, Siginma Duasi", "YG"},
        {"Sana iman etmis bu kuluna azap mi edeceksin? Sana gonlunu veren bu muhtac gedayi uzakligin yakici atesine mi maruz birakasin? Dusmus kalkimis ama gelip af talebinde bulunmus bu zavalli kulunu kapindan kovacak misin? Rabbim bilirsin ki, ben Senin rizandan baska bir sey istemiyorum. Kerem kapinda el actigim tek varlk Sensin. Baskasinin kapisindan donmeyecegi kalbim bilir; zira butun kapilar Senin kapina cikar.", "Yakaran Gonuller, Munacat", "YG"},
        {"Allahim, uzerimden ltuflarin kaldirma. Rahmetinin gelip beni de sarip sarmalayacagi hususunda umitsizlige dusturme. Gorup gozetmenden ve yakinligindan beni mahrum etme. Hayatimin hicbir zaman diliminde rahmetin ve sefkatin hususunda yeis gibi bir cikmaza dusmemem icin hep elimden tut! Tut elimden Allahim, tut ki edemem Sensiz! Bendeni kuvetlendir ki dusamam Sensiz!", "Yakaran Gonuller, Yalvaris", "YG"},
        {"Rabbimiz, uzerimzdeki nimetini tamamla. Bize yalnizken veya bir toplulukta bulunurken gece-gunduz acik-gizli rahatlikta-zorlukta hep Senin yadinla oturup kalkmay nasip et. Bizi hep dupduru, katisiksiz amellerde istihdam eyle. Kusur ve gunahlarimizi da ince hesaba tabi tutma ve ne kadar hatamiz varsa bagisla. Seni layik oldugun sekilde sena edebilmemiz mumkun degildir. Zira Sen Yuce Zatini nasil sena etmissen oyle bir senaya layiksin.", "Yakaran Gonuller, Nimet Duasi", "YG"},
        {"Ey Yuce Rabbim! Uzerimideki lutuflarin o kadar cok ki, onlara bakinca gunahlardan en uzak durmasi gereken kisi oldugum katiyen zuhur eder. Iste huzurundayim; kucuk zelil hor ve hakirim. Korku ve hasyetten iki buklum oldum. Isleyip sirtima yukledigim buyuk gunahlari ve butun curumleri huzurunda itiraf ediyorum. Ediyor ve musamahana siginiyorum. Rahmetine iltica ediyorum. Yakinen biliyorum ki Senden baska hukmunu uygulamaktan engelleyebilecek hicbir guc yoktur.", "Yakaran Gonuller, Itiraf Duasi", "YG"},
        {"Ey zikriyle ihlas sahiplerinin unsiyete erdigi Rabbim, ey kulluk yolunun yolcularini sirat-i mustakime erdiren Allahim, hayatini Allah sevgisi yorungeli surdurenler cenneti helal kilan Rabbim, subhansin. Zifiri karanlik gecede siyah karincanin ayak hareketlerini goren Allahim subhansin. Ilm-i ezelisi ile butun mahlukatinin alip verdigi nefeslerin sayisini bilen Rabbim subhansin.", "Yakaran Gonuller, Tesbih Duasi", "YG"},
        {"Allahim! Dinim dunyam ailem ve malimda Senden afv u afiyet diliyorum. Ayiplarimi ort ve beni korktuklarimdan emin eyle. Onumden arkamdan sagimdan solumdan ve ustumden gelebilecek tehlikelerden beni koru. Ayaklarimin altindan derdest edilmekten de Senin azametine siginirim. Rab olarak Allahtan, din olarak Islamdan, Resul olarak da Hazreti Muhammeden razi olduk.", "Yakaran Gonuller, Afiyet Duasi", "YG"},
        {"Ya Rab, Sen O Efendiler Efendisine salat ve selam eyle. Onu evvelkilerin ve sonrakilerin gipta ile bakislarini odakladigi Makam-i Mahmuda eristir. Dunyada Onun sanini yucelt. Dinini takviye ederek ila buyur. Getirmis oldugu semavi sistemi ebediyete kadar dipdiri olarak yasat. Ahirette ummetine sefaat etmesine musaade buyur. Ecir ve sevabini bol eyle.", "Yakaran Gonuller, Salavat Duasi", "YG"},
        {"Ey sonsuz comertlik ve ihsanda bulunan Rabbim! Ey kullarica fazlindan sayisiz nimetler yagdiran! Ey mumin kullarinin gonullerini emn u emanla dolduran! Ey Kendisi her turlu kainattaki nezafet ve temizligin de kaynagi olan! Ey her seyi yerli yerinde hikmetle yerlestiren ve varligin mimarisini beyaniyla resmeden! Ey rahmeti sonsuz ve emrince kulluk eden kullarindan razi ve hosnut olan!", "Yakaran Gonuller, Esma Duasi", "YG"},
        {"Allahim! Nurun tastamam oldu, hidayet buyurdun, hamd olsun Sana. Hilmin oyle engin ki bagisladin hamd olsun Sana. Nimetlerini bol bol bahsettin hamd olsun Sana. Senin kerem ve serefin butun sereflerin ustunde, sanin da topyekun nam u nisanlarin otesindedir. Ihsanlarin hem en buyuk hem de kullarin icin en mesakkatsizdir. Rabbimiz Sana itaat edilir Sen de takdir buyurup karsiligini verirsin. Isyan edilir onu da bagislarsn.", "Yakaran Gonuller, Hamd Duasi", "YG"},
        {"Allahim! Beni nehyettigin, uyardigin ve deliller serdederek ikaz buyurduguna ragmen nefsani arzularimi Sana kullugun onunde tutup kendi isteklerimi Senin emirlerinin onune gecirerek irtikap etmis oldugum gunahlardan dolayi magfiretini diliyorum. Ya Rabbi bilerek ya da bilmeyerek islemis oldugum her gunahima kar magfiretinle muamele et. Yargilama beni, affet beni, bagisla beni.", "Yakaran Gonuller, Istigfar Duasi", "YG"},
        {"Ey her seye sah damarindan daha yakin olan Karib! Ey zahir-batin her seyi gorup kontrol eden Rakib! Ey muhabbet erlerinin Yuce Zatini yine Zati icin sevip inkiyad ettikleri Habib! Ey dualara icabet eden ve isteklere mukabelede bulunan Mucib! Ey her seye yeten ve herkesin hesabini gorecek olan Hasib! Ey gorunen ve gorunmeyen hastaliklara sifa ihsan eden Tabib! Ey her seyi Zatina mahsus basarla goren Basir!", "Yakaran Gonuller, Esma-ul Husna Duasi", "YG"},
        {"Allahim! Senin inayetinle sabahladik; Senin inayetinle aksamladik; Senin inayetinle yasar, Senin izninle oluruz. Donus de Sanadir. Hamd canimizi aldiktan sonra bizi tekrar dirilten Allaha mahsustur. Donus de Onadir. Allahim Senden baska ilah yoktur. Seni yuce sanina yarasmayacak her eksiklikten tenzih ederiz. Her sabah ve her aksam Sana hamd eder, Sana sukr ederiz.", "Yakaran Gonuller, Sabah-Aksam Duasi", "YG"},
        {"Recahi hislerimi tamamiyla Senin inayetine rahmetine sefkatine bagladim; ne olur bu aciz kulunu haybet ve husrandan koru. Ey benim Yuce Rabbim! Ne olur dualarimla Senin arana perde koyma, dileklerimi geri cevirme ve beni hicranmla bir hic hukmunde olan havl ve kuvvetsizligimle bas basa birakma! Acziyetime ihtiyacima merhamet et! Gizlimi de acigimi da bilen Sen, faydayi celb, zarari defedecek Sen.", "Yakaran Gonuller, Iltica Duasi", "YG"},
        {"Allahim! Yuce Kitabinda zikrettigin yahut kullarindan herhangi birine bildirdigin ya da kimseye bildirmeyip nezddi uluhiyetinde istisar buyurdugun butun isimlerini hurmetine sana yalvariyorum. Kurani kalbimin bahari, gogsumun nuru, huzunlerimin devasi, gam ve kederlerimin ilaci kil. Kuranla kalbimi dirilt, gozumu aydinlat, dilimi guzellesstir.", "Yakaran Gonuller, Kuran Duasi", "YG"},
        {"Ey ziddi olmayan tek Ehad! Ey misli ve niddi olmayan Ferd! Ey butun kusurlardan beri olan ve her sey Kendisine muhtac bulunan Samed! Ey ikincisi esi benzeri olmayan Vitr! Ey hicbir zaman bir vezir muin ve yardimciya ihtiyac duymayan Rabb! Ey hicbir kimseye ve hicbir seye muhtac olmayan Ganiyy! Ey Kendisini azledecek bir merci ve makam katiyen bulunmayan sermedi Sultan!", "Yakaran Gonuller, Tevhid Duasi", "YG"},
        {"Allahin adi ile ki O benim her seyime kafidir. Ondan baska bir ilah yoktur. Her seye sahittir. O Allahtir. Neyi nasil dilerse o oyle olur. O benim Rabbimdir. Sani cok yucedir. Ulular Ulusudur O. Ben sadece Ona tevekkul ettim ve ederim. Onlara karsi Allah sana yeter. O Semi ve Alimdir, her seyi isitir her seyi bilir. Subhansin butun kusurlardan berisin. Eman diliyorum Senden el-eman el-eman!", "Yakaran Gonuller, Tevekkul Duasi", "YG"},
        {"Allahim! Senden bu gunun hayrini fethini yardimini nurunu bereket ve hidayetini istiyor, bugunde ve bundan sonraki gunlerde olan ve olacaklarin serrinden Sana siginiyorum. Allahim imani bize sevdir ve onu kalblerimizde tezyin et. Kufur fisk ve isyani da bize cirkin goster ve bizi hep dosdogru yolda yuruyenlerden eyle.", "Yakaran Gonuller, Gunluk Dua", "YG"},
        {"Ey Hayy u Kayyum! Rahmetin hurmetine Senden yardim dileniyorum; her halimi islah buyur ve goz acip kapayincaya kadar olsun beni kendime ve nefsime terk etme. Allahim! Adi anilmaya en layik olan Sen, kullukta bulunulmaya en layik olan da yine Sensin. Sensin yardim istenilenlerin en cok yardim edeni, guc sahiplerinin en sefkatlisi, kapisinda bir seyler dilenilenlerin en comerdi.", "Yakaran Gonuller, Istiaze Duasi", "YG"},
        {"Allahim! Senden faydasiz ilimden, husu duymayan kalpten, doymayan nefisten ve kabul olmayan duadan Sana siginirim. Korkulugun en kotusunden, hayatin en kotusunden ve fitneden Sana siginirim. Allahim ilmimi artir, kalbimi kaydrma. Katindan bana rahmet bagisla. Suphe yok ki bagislari bol olan Sensin.", "Yakaran Gonuller, Siginma ve Istek Duasi", "YG"},
        {"Allahim! Seni yuce sanina yarasmayacak her eksiklikten tenzih ederim. Sana hamd ederim. Senden baska ilah olmadigina sahitlik ederim. Senden magfiret diler ve Sana donerim. Ne olur butun gunahlarimizi yarlga ve tevbemizi kabul buyur. Perdemizi ort, ayplarimizi gizle. Bizi Sana layik kul eyle. Sana layik kul olamiyorsak, hic degilse Sana kul olmak icin caba gosteren kullarindan eyle.", "Yakaran Gonuller, Meclis Duasi", "YG"},
        {"Kuslarin yuvalarinda Kendisini tesbih ettigi Rabbim, vahsi hayvanlarin issiz yerlerde Zatini yucelttigi Allahim, kullarin acik ve gizli hep Kendisini tesbihte bulundugu Rabbim. Muminlerin islerini inayet ve nusretiyle cepecevre saran Allahim subhansin. Titreyen kalbler ancak Senin zikrinle itminan bulur ve zararlardan kurtulur. Rabbim her varlik Seni anar, her nefes Seni zikreder.", "Yakaran Gonuller, Tesbih Namesi", "YG"},
        {"Biz de butun mulk de Alemlerin Rabbi Allaha ait olarak sabahladik. Allahim Senden bu gecenin hayrini fethini yardimini nurunu bereket ve hidayetini istiyor bu ve bundan sonraki gecelerde olan ve olacaklarin serrinden Sana siginiyorum. Allahim imani bize sevdir ve onu kalblerimizde tezyin et. Kufur fisk ve isyani da bize cirkin goster ve bizi hep dosdogru yolda yuruyenlerden eyle.", "Yakaran Gonuller, Aksam Duasi", "YG"},
        {"Allahim! Guce ve kuvvetine, her seye kadir olduguna ve her seyi Onun yaptigina iman ediyorum. Cenab-i Hakkin gucune ve kuvvetine, her seye kadir olduguna sonsuz iman ediyorum. O Zat ki gokleri ve yeri yoktan var etti. Her seyin anahtari Onun elindedir. Her kapi Onun izniyle acilir. Her dügüm Onun kudretiyle cozulur. Her zorluk Onun inayetiyle kolaylasir.", "Yakaran Gonuller, Iman Duasi", "YG"},
        {"Allahim! Adinda sifa olan, zikriyle dertlere sifa bulunan Rabbim. Gorünen ve gorunmeyen hastliklara sifa ihsan et. Bedenimin hastaligina sifa ver, kalbimin hastaligina deva ver, ruhumun yarasina merhem ol. Senden sifa diliyorum, Sen Safisin. Senden afiyet diliyorum, Sen Muafisin. Senden rahmet diliyorum, Sen Rahimsin. Hastaligimdaki hikmetini gosterme, sadece sifani ver Rabbim.", "Yakaran Gonuller, Sifa Duasi", "YG"},
        {"Allahim! Gazabindan rizana, cezandindan afiyetine siginirim. Senden yine Sana siginirim. Sana geregi gibi hamd etmekten acizim. Sen kendini ovdugun gibisin. Seni geregi gibi ovmekten aciz oldugumu itiraf ederim. Ya Rabbi Sen ovulmeye layik olansin, bense ovguyu bilmeyenin. Sen sevilmeye layik olansin, bense sevgiyi bilmeyenim. Ama yine de Seni seviyorum ve Sana ovguler sunuyorum.", "Yakaran Gonuller, Hamd ve Iltica", "YG"},
        {"Allahim! Beni muminlere kol kanat germeye ve her zaman onlara karsi mulayemetle davranmaya muvaffak kil. Kalbim katidir; itaatkar kullarina karsi Senin hosnutlugun ve ahiret istikametinde yumusaklatir. Dilimi hayira ac, serrden kapat. Elimi hayira uzat serrden cek. Ayagimi hayra yurut serrden dur. Butun uzuvlarimi Senin rizana uygun kullan.", "Yakaran Gonuller, Ahlak Duasi", "YG"},
        {"Allahim rahmetine siginiyor, kullaridna bildirdigin yahut bildirmeyip nezdinde tuttugun butun guzel isimlerinle Sana yalvariyorum. Kuranim kalbimin bahari, gogsumun nuru, huzunlerimin devasi, gam ve kederlerimin ilaci kil. Allahim gunahlarimi yarliga ve tevbemi kabul buyur. Percemini yed-i kudretinde tuttugum her seyin serrinden Sana siginiyorum.", "Yakaran Gonuller, Ismi Azam Duasi", "YG"},

        // ========== KULLI KAIDELER (40) ==========
        {"Bismillah her hayrin basidir. Her hayirli ise Bismillahirrahmanirrahim ile baslanmalidir. Besmelesiz baslanan isler sonunda neticesiz kalmaya mahkumdur. Hayirli olmayan islere Besmele cekilmez. Mademki hayirli olmayan islere Besmele cekilmez ve Besmelesiz baslanan isler hayirli netice vermez, o halde her isimize Besmele ile baslamali ve Besmele cekilmeyen islerden uzak durmaliyiz.", "Kulli Kaideler, Sozler, 1. Soz", "KK"},
        {"Kainatta her seyin bir kemal noktasi ve o seyin o noktaya dogru bir meyli vardir. Katlanmis meyil ihtiyac, katlanmis ihtiyac istiyak, katlanmis istiyak incizap olur. Bunlarin hepsi Cenab-i Hakkin tekvini emirlerinin esyanin mahiyetindeki cekirdekleri ve bu emirlere itaat merkezleridir. Her varlik kendisi icin tayin edilmis kemal noktasina dogru ilerler. Bu ilerleys Allahin iradesinin eserdeki tezahürudür.", "Kulli Kaideler, Sozler", "KK"},
        {"Nur-u akil kalbden gelir. Gozun karasi gece fakat isikli gece, beyazi ise gunduz fakat karanlik gunduz gibidir. Kalbin isigi yani iman olmazsa sadece dimagin urunu olan fikir hicbir zaman aydinlatici olamaz. Bilgi ve dusunce iman olmadan sadece kapkaranlik cehalet fiskirtir. Iman olmayan ilim ruhsuz bedendir. Akil tek basina yeterli degildir; kalbin nuru ile aydinlanmadikca dogru yolu bulamaz.", "Kulli Kaideler, Sozler", "KK"},
        {"Bir seyin varligin, onun icin gerekli butun sartlarin sebeplerin ve ayrica butun parcalarinin varligina baglidir. Yok olmasi ise bu sart sebep ve parcalrindan bir tekinin yoklugu ile mumkundur. Bir cumlenin varligi onu meydana getiren butun kelimelerin hatta harflerin varligina baglidir. Tek bir harfin yoklugu butun cumleyi yok edebilir. Yaratmak icin sonsuz guc, yikmak icin bir parmak yeter.", "Kulli Kaideler, Sozler", "KK"},
        {"Iman hem nurdur hem kuvvettir. Evet hakiki imani elde eden adam kainata meydan okuyabilir ve imanin kuvvetine gore hadiselerin tazyikindan kurtulabilir. Tevekkul ile dunya gemisine biner rahatla yolculuk yapar. Iman insani sultan eder. Imansiz insan en zayif en aciz bir varlik olur. Imanli insan ise kainatin efendisi olur. Bu fark sadece bir kelimelik fark degil, sonsuz ile sifir arasindaki farktir.", "Kulli Kaideler, Sozler, 23. Soz", "KK"},
        {"Dunya bir misafirhanedir. Insan ise onda az duracak bir misafirdir. Ve vazifedar bir yolcudur. Baki olan ve seni bekleyen cok guzel ve yuksek bir saadet seni cezbedip kendine cekiyor. Eger akil varsa ey nefsim bu sonsuz saadeti kaybetme. Misafirhane icin agalama, ev zannetme. Burada kalici degilsin. Asil vatanin ahirettir. Orasi icin hazirlik yap. Buradaki her sey gecicidir, oradaki her sey kalicidir.", "Kulli Kaideler, Sozler, 11. Soz", "KK"},
        {"Sabir uc turludur: Birincisi gunahlara karsi sabir. Ikincisi ibadetlere devam etmede sabir. Ucuncusu musibetlere karsi sabir. Her uc nevi sabir de buyuk sevap kazandirir. Sabreden muzaffer olur. Sabir acilarin en acisi gibi gorunur ama meyvelerin en tatlisini verir. Sabirsiz insan aceleci, aceleci insan hatali, hatali insan pismandlr. Sabir zaferin anahtaridir. O anahtar olmadan hicbir kapi acilmaz.", "Kulli Kaideler, Mektubat, 29. Mektup", "KK"},
        {"Her musibette bir nimet cephesi vardir. Bir nimet ki senden alinmis yerine daha buyugu konulacaktir. Musibetler gunahlara kefaret olur. Sabir ile mukabelede bulunan derecat kazanir. Musibet tarlasinda sabir tohumu ekilir, sukur suyu ile sulanir ve rahmet meyvesi hasat edilir. Her dert bir kapinin anahtaridir. O kapi acilmadan icindeki hazineye ulasilamaz.", "Kulli Kaideler, Lemalar, 2. Lema", "KK"},
        {"Kainat bir kitab-i kebirdir. Her bir harfi yuzlerce kelime, her bir kelimesi yuzlerce satir, her bir satiri yuzlerce sayfa, her bir sayfasi yuzlerce kitap degerini ifade eder. Ve o kitaptaki cumleler birbirine bakiyor. Kainattaki her bir varlik diger varliklara baglidir. Her bir yaprak bir agaca, her bir agac bir ormana, her bir orman bir ekolojiye, her bir ekoloji tum kainata isaret eder.", "Kulli Kaideler, Sozler, 25. Soz", "KK"},
        {"Namaz butun ibadetlerin fihristi ve kudsi bir haritasidir. Namazda ruku ve secde ile insan kendi aczini zaafini ve fakrini Cenab-i Hakkin kudret ve azameti karsisinda ilan eder. Namaz kulun Rabbine en yakin oldugu andir. Secdeye kapanan insan en yuksek makama cikar. Cunku o an benligini birakir, aczini ilan eder ve sonsuz kudret sahibine teslim olur. Bu teslimiyet insani yuceltir.", "Kulli Kaideler, Sozler, 9. Soz", "KK"},
        {"Sukur nimeti ziyadelesstirir. Sikayet ise nimeti kacirir. Elindeki nimete sukret ki buyusun. Baskalarinin elindekine bakma ki huzurun kaybolmasin. Sukur eden az ile cok eder, nankur eden cok ile az eder. Sukur bir bakima nimeti gormektir. Gormek artmasina sebeptir. Gormemek ise kaybolmasina yol acar. Gozunu acip nimete bakan sukur etmis olur; gozunu kapayip sikanet eden nimetten mahrum kalir.", "Kulli Kaideler, Mektubat, 28. Mektup", "KK"},
        {"Olum fena ve zeval degil belki terhis ve tahliyedir. Ebedi saadetin baslangicidir. Mumin icin olum karanlik bir kuyu degil nurlu alemlere acilan bir kapidir. Kabirden sonraki hayat bu dunyadakinden kat kat daha guzeldir. Olumden korkmak manasizdir. Cunku olum bir son degil bir baslangictir. Tohumun topraga dustugu an cürumesi degil filizlenmesidir. Olum de insanin ahirete filizlenmesidir.", "Kulli Kaideler, Sozler, 1. Soz", "KK"},
        {"Esya veya varliklarin vucuda gelislerinde mutlak bollukla beraber mukemmel uyum ve intizam vardir. Sinirsiz bir suratle beraber tam bir duzen tenasup denge ve israfsizlik; mutlak coklukla beraber mukemmel sanat ve guzellik; mutlak kolaylikla beraber mukemmel maharet ihtimam ve kusursuzluk vardir. Butun bunlar Cenab-i Allahin varligini birligini nihayetsiz Ilim Irade ve Kudretini apacik gosterir.", "Kulli Kaideler, Sozler, Allah'in Varligi", "KK"},
        {"Hayat Cenab-i Allahin varligina ve Birligine, olum ise Onun bekasina delildir. Her an milyarlarca canli varlik hayata gonderilmekte ve milyarlarcasi hayattan alinmaktadir. Gunes altinda akip giden bir nehrin yuzundeki kabarciklarda birbirinin aynisi gunescikler parlar. Nehrin gunesle irtibati kesildiginde kabarciklardaki gunescikler gorunmez olur. Bu gosterir ki parlayan gunescikler semadaki tek bir gunese aittir.", "Kulli Kaideler, Sozler, Tevhid", "KK"},
        {"Her kim kendisini Allaha mal ederse butun esya onun lehinde olur. Ve kim Allaha mal olmasa butun esya onun aleyhinde olur. Allaha mal olmak ise butun esyayi terk ve her seyin Ondan oldugunu ve Ona rucu ettigini bilmekle olur. Colde sozi gecen bir asiret reisinin ismini almadan dolasan haramilere yem olur. Bunun gibi kainatin Sahibine intisap etmeden dunyada dolasan da tehlike icindedir.", "Kulli Kaideler, Sozler, 1. Soz", "KK"},
        {"Izzet ve Azamet ister ki esbap perdedar-i dest-i Kudret ola akli nazarinda. Tevhid ve Celal ister ki esbap elini ceksin tesir-i hakikiden. Sebepler sadece Allahin Izzet ve Azametinin onunde birer perdedir. Neticeyi yaratan veya hasil eden daima Allahtir. Sebepler gosteris icin konulmus perdelerdir. Perdenin arkasindaki guc, tek ve mutlak guctur. Sebeplere tapmak perdelere tapmaktir.", "Kulli Kaideler, Sozler, Tevhid", "KK"},
        {"Dimgda ilmin mertebeleri vardir ve bu mertebeler birbiriyle ic ice olup cok defa birbirine karistirilir. Dimgda uretilen her sey ilim degildir. Ilim dimag ile birlikte kalbin urunudur ve kesinlik tasir. Kalbin isiginda yol alan dimada uretilen ilim insani imana ve Allaha derin saygiya goturur. Ilim ile iman birbirine ozdes gorulebilir. Fakat nice bilen vardir ki bildigini yasamaz, tatbik etmez.", "Kulli Kaideler, Sozler, Ilim Bahsi", "KK"},
        {"Hazmolmayan ilim telkin edilmemeli. Gercek yol gosterici alim koyun gibi olur kus gibi olmaz: koyun kuzusuna hazmolmus tertemiz sutunu, kus ise yavrusuna kusmugunu verir. Ilim kesinlik ifade eder. O asla malumat degildir. Malumat ilmin malzemesidir; vucuda girmeyi bekleyen yiyecek gibidir. Yiyecek hazmedilmeden gida olmaz. Malumat da hazmedilmeden ilim olmaz.", "Kulli Kaideler, Sozler, Ilim Bahsi", "KK"},
        {"Sabit bir hakikatin tersine donmesi muhaldir. Bundan daha muhal olan bir hakikatin kendi zitti olmasidir. Ates Cenab-i Allahin kendisine verdigi yakicilik sebebiyle daima yakar ve mucize kabilinden Allah'in farkli tesir yaratmasi disinda hicbir zaman usutmez. Hakikatler degismez. Degisen insanlarin bakis acisidir. Gunes her gun aynidir; degisen bizim ona bakisimizdir.", "Kulli Kaideler, Sozler, Hakikat Bahsi", "KK"},
        {"Hak aldatmaz; hakikati goren aldanmaz. Hak olan bir meslek hileden mustagnidir. Hakikati gorenin gozune hayalin ne haddi var ki hakikat gorunup aldatsin? Hak ve hakikat hicbir zaman aldatmaz. Vahiy ve peygamberlik haktir, onda batila asla yer yoktur. Butun peygamberlerin birinci sifati sidk yani dogruluktur. Yalan soyleyen hicbir peygamber olmamistir ve olmayacaktir.", "Kulli Kaideler, Sozler, Hakikat Bahsi", "KK"},
        {"Cenab-i Allaha inanip dayanan bir cuz iken kull hukmune gecer ve ona gore guc kazanir. Seffaf ve parlak kibrit basi kadar bir zerrecik kendi basina kalsa hicbir nur sahibi olamaz. Fakat kendini gunese tutsa butun bir gunesi adeta icine alabilir. Iste insana da Allah'a dayaninca butun kainat guc verir. Dayanmazsa bir yaprak kadar bile gucü kalmaz.", "Kulli Kaideler, Sozler, Tevhid", "KK"},
        {"Vicdan cezbesi ile Allahi tanir. Insani caresiz kaldigi anda Allaha yonelten Allah'a dogru ceken vicdanidir. Cunku vicdan eger tamamen tefessuh etmemis ve bir yilan-ciyan-akrep yuvasi haline gelmemisse kendisiyle bas basa kaldigi anlarda Allahi gosterecek ve insani Allaha yonlendirecektir. Vicdan kalbin sesidir. O sesi bastirmayan dogru yolu bulur.", "Kulli Kaideler, Sozler, Vicdan Bahsi", "KK"},
        {"Fitrartin sehadeti sadikadlr. Insanlarin ve cinlerin disinda kalan butun kainatta cebir vardir; yani butun kainat Cenab-i Allahin hukumlerine kanunlarina kayitsiz sartsiz itaat halindedir. Bundandir ki insanlarin mudahale sahasi disinda kalan butun kainatta her eser mukemmeldir. Bir agacin onca yapragi arasinda renk acisindan ton farki bile bulunmaz.", "Kulli Kaideler, Sozler, Fitrat Bahsi", "KK"},
        {"Bir meyve agacin kucultulmus misali veya modelidir. Meyvedeki cekirdek agacin amel defteri olup agacin tarih-i hayati cekirdekte kayitlidir. Bir meyve agacin tamamiyla belki o agacin turuyle hatta butun yerkureyle ilgilidir. Bir meyvenin sanatindaki azamet ve ihtisam yerkure buyuklugundedir. Meyveyi yapan elbette yerkureyi de yapmaktan aciz degildir.", "Kulli Kaideler, Sozler, Sanat-i Ilahi", "KK"},
        {"Bir seyi bir sifatla niteleyenin o sey olmasi gerekmez. Cicekler renkleriyle gunesi tavsif eder yani gunesin isigindaki renkleri gosterir. Fakat bu ciceklerin gunesin kendisi olmasini gerektirmez. Ruh varligi vucutla munasebeti ve fonksiyonlariyla Cenab-i Allahi tanimaya onemli bir misal teskil eder; fakat ruh hicbir zaman Allah olamaz. Delil olan delalet ettigi seyin kendisi degildir.", "Kulli Kaideler, Sozler, Tevhid", "KK"},
        {"Variklarin her bir turune dair bir ilim dali tesekul etmistir. Her bir ilim kendine ait kanun denilen kulli kaidelerden ibarettir. Kanun veya kulli kaidelerin varligi mutlak nizam ve intizama isaret eder. Bu nizam da Nazimi yani Nizami Kuran ve Devam Ettireni gosterir. Kainat ile ilgilenilmesi ve ondaki kanunlarin kesfedilmesi Cenab-i Allahin varliginin en buyuk delillerindendir.", "Kulli Kaideler, Sozler, Ilimler ve Tevhid", "KK"},
        {"Kurani Kerime ve imana ait her sey, zahiren kucuk gorunenleri de dahil olmak uzere, kiymetce buyuktur. Evet ebedi saadete yardim eden kucuk degildir. Insan vucudundaki bir hucrenin sagligini kaybetmesi kanser gibi butun vucudu tehdit eder. Bunun gibi imanin en kucuk bir meselesi bile butun ebedi saadet binasinin temeli olabilir. Kucumseme, buyuk kayiplarin sebebidir.", "Kulli Kaideler, Sozler, Iman Bahsi", "KK"},
        {"Kuran beser aklina tenezzulat-i Ilahidir. Yani Cenab-i Allah en basitinden en yuksegine kadar butun seviyelere birden hitap eder. Fakat insanlarin cogu avam oldugundan oncelikle avamin anlayis kapasitesini nazara alir. Bununla birlikte her donemde her zemin zaman ve sartta her seviyeyi ikna ve tatmin eder. Kuran bir okyanus gibidir; cocuk kenarinda oynar, dalgin derinliklerine yuzar.", "Kulli Kaideler, Sozler, Kuran Bahsi", "KK"},
        {"Bir seyin neticesi meyvesi o seyden once dusunulur. Demek ki varlik sahasina cikmada en son olan manen en evveldir. Rastgele bir bina yapip sonra ona fonksiyon bicmeyiz. Bir binayi nicin hangi maksat istikametinde yapacaksak zihnimizde once binadan gaye bulunur. Sonra bu gayeye gore zihnimizde binaya sekil veririz. Ayni sekilde kainatin da bir gayesi vardir ve o gaye insandir.", "Kulli Kaideler, Sozler, Gaye Bahsi", "KK"},
        {"Kainatta bile redd-i mudahale kanunu vardir. Bu sebeple amiriyet ve hakimiyet rakip ve ortak kabul etmez, mudahaleyi reddeder. Her bir varligin menseli tek bir butundur. Bir olan birlik teskil eden bir halde bulunan ancak Birden cikar. Kainattaki ve esyadaki bu birlik tek bir Yaratici ve Mudebiri isaret eder. Iki sultan bir ulkede olamaz; kainatin sultani da tektir.", "Kulli Kaideler, Sozler, Tevhid", "KK"},
        {"Hareketin bittigi noktada dusunce, dusuncenin bittigi noktada hareket baslar. Aksiyon ve dusunce insan hayatinin ozeti gibidir. Bunlar birbirine sebeptir birbirini dogurur ve birbirini tamamlar. Peygamber Efendimize gelen ilk vahiy bir aksiyon emriydi: Oku! Demek ki peygamberlik aksiyonunun belki butun Islami aksiyonun adi okumaktir. Kainati okumak insani okumak Kurani okumak.", "Kulli Kaideler, Sozler, Aksiyon Bahsi", "KK"},
        {"Ey nefis! Bu dunyada senin icin iki yol var: Biri selamet ve saadet yolu olan iman ve taat yolu. Digeri felaket ve sefalet yolu olan isyan ve dalalet yolu. Sen hangisini secersin? Bu secim her gun her saat her an onumuze cikar. Her karar bir secimdir. Her secim bir yondur. Yanlsi yonu secen uzaklasir, dogru yonu secen yakinlasir. Yol iki, secim senin. Ama sonuc Allahin.", "Kulli Kaideler, Sozler, 13. Soz", "KK"},
        {"Insanin en buyuk vazifesi iman etmek ve dua etmektir. En buyuk kusuru ise iman zayifligi ve ihmal ile ibadeti terk etmektir. Sonsuz acizligin ve fakrin ile beraber sonsuz bir kudrete dayaniyorsun. Iman ettikten sonra en buyuk ibadet duadir. Dua ibadetin ozu ve ruhudur. Dua yapmayan insan kullugunun farkinda degildir. Dua edin; cunku dua kulun Rabbine en yakin oldugu haldir.", "Kulli Kaideler, Sozler, 23. Soz", "KK"},
        {"Hakiki saadet ve huzur ancak imanda ve iman hakikatlerini yasamaktadir. Imansiz ilim ruhsuz vucuttur; imansiz hayat meyvasiz agactir. Iman kalbin hayatidir. Iman ruhun gidasidir. Iman vicdanin nurudur. Iman olmadan ne ilim fayda verir ne amel deger kazanir ne de hayat anlam tasir. Her sey imanla anlam kazanir. Imansiz kainat bir zindan, imanla kainat bir mektep olur.", "Kulli Kaideler, Asa-yi Musa", "KK"},
        {"Kuranin her bir tarafina dagilmis olan maksatlari ve asli unsurlari dort tanedir. Onlar da Saniin Birligini ispat peygamberlik cismani hasir ibadet ve adalettir. Bu dort esas Kuranin butun surelerinde dolaylI veya dogrudan islenmir. Tevhid her seyin temelidir. Peygamberlik rehberliktir. Ahiret hesap gunudur. Ibadet ve adalet ise yasama bicimdir.", "Kulli Kaideler, Sozler, Kuran Bahsi", "KK"},
        {"Kuran ayna ister vekil istemez. Kitaplar Kurana durbun olmali Onun yerine gecmemeli. Insanlari genelde harekete sevkeden onlardaki Allah'a Peygambere ve Kurana olan iman, bu imanin kalblerde meydana getirdigi sevk ve sevktir. Insanlara dogruyu nasil davranmalari gerektigini teblig etmenin en iyi ve en tesirli yolu onlari dogrudan Kuranla ve Sünnetle bulustrmaktir.", "Kulli Kaideler, Sozler, Kuran Bahsi", "KK"},
        {"Her bir fen bir veya birkac Ilahi Isime dayanmakla da Cenab-i Allahin varligini ve Birligini ispat eder. Yeryuzu icinde bulunan milyonlarca turde ot bitki agac ve hayvanlara essiz bir eczanedir. Yeryuzu eczanesi mükemmel eczaneden ne kadar daha mukemmel ve muazzamsa bu ikinci eczanenin Yaraticisina Hakimi Zulcelal Farmakologuna isaret eder. Her ilim dalinin arkasinda bir Ilahi Isim vardir.", "Kulli Kaideler, Sozler, Ilimler ve Tevhid", "KK"},
        {"Sadece bir agacin hatta bir cicegin bile yaratilmasinda o derece harika bir intizam bir sanat bir hikmet vardir ki kainattaki butun sebepler butun kanunlar butun insanlar bir araya gelebilecek olsalar yine de onu taklit edip bir agac yaratamazlar. Insan Cenab-i Allahin kendisine verdigi kabiliyetleri kullanarak bir seyler uretir; sonra da yaptiklarnia bakarak her seyi yapabilecegini zanneder.", "Kulli Kaideler, Sozler, Sanat-i Ilahi", "KK"},
        {"Kuranin kapsami derinligi ve Kurandaki denge baska hicbir sozde bulunmaz. Kuran sonsuzca bir kapsam ve derinlige sahip oldugu gibi bu kapsam ve derinlikte ele aldigi meseleler arasinda da dengeyi tam gozetmistir. Bu denge Kuranin Allah Kelami oldugunu gosteren en onemli delillerden biridir. Hicbir insan eseri bu denli derin bu denli kapsamli ve bu denli dengeli olamaz.", "Kulli Kaideler, Sozler, Kuran Bahsi", "KK"},
        {"Nazar zevki bir meselede tasarruf etse onu bozar. Zevketmek yoluyla ve kesfen ulaasilan sonuclar, gorus ve dusuncenin terazisinde tartilmazsa katilasr ve cirkinlesir. Zevken ve kesfen ulasilan sonuclar ve manalar uzerinde akil yurutulmez; onlar gorus ve dusunce mercegi altinda incelenmez. Boyle yapilacak olsa soz konusu sonuclar ve manalar bozulur, catlar veya kaybolur.", "Kulli Kaideler, Sozler, Zevk Bahsi", "KK"},
    };

    public static int getCount() {
        return ENTRIES.length;
    }

    public static String getText(int index) {
        return ENTRIES[index % ENTRIES.length][0];
    }

    public static String getSource(int index) {
        return ENTRIES[index % ENTRIES.length][1];
    }

    public static String getCategory(int index) {
        return ENTRIES[index % ENTRIES.length][2];
    }

    public static String getNarrator(int index) {
        String cat = getCategory(index);
        if (cat.equals("FR")) return "Abdulkadir Geylani (k.s.)";
        if (cat.equals("KK")) return "Bediuzzaman Said Nursi (r.a.)";
        return "";
    }

    public static String getBadgeText(int index) {
        String cat = getCategory(index);
        if (cat.equals("FR")) return "Fethur-Rabbani";
        if (cat.equals("YG")) return "Yakaran Gonuller";
        if (cat.equals("KK")) return "Kulli Kaideler";
        return "";
    }

    public static int getBadgeColor(int index) {
        String cat = getCategory(index);
        if (cat.equals("FR")) return 0xFFD4B872;
        if (cat.equals("YG")) return 0xFF4FC3F7;
        if (cat.equals("KK")) return 0xFFCE93D8;
        return 0xFFFFFFFF;
    }

    public static int getRandomIndex() {
        return random.nextInt(ENTRIES.length);
    }
}
